export const actionTypes = {
    SET_PLACE: "SET_PLACE",
    SET_PAGE: "SET_PAGE",
    SET_TOTAL: "SET_TOTAL",
    SET_FLATS: "SET_FLATS",
    SET_FAVORITES: "SET_FAVORITES",
    SET_FAVORITES_IS_CLICKED: "SET_FAVORITES_IS_CLICKED",
    SET_MODAL_IS_OPENED: "SET_MODAL_IS_OPENED",
    SET_MODAL_FLAT: "SET_MODAL_FLAT",
    GET_RESULT: "GET_RESULT",
    LOAD_MORE: "LOAD_MORE",
    ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
    REMOVE_FROM_FAVORITES: "DELETE_FROM_FAVORITES"
};
